package com.bd.model;

import java.io.Serializable;
import java.util.Date;

public class Resource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.resourcetype
     *
     * @mbggenerated
     */
    private Integer resourcetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.lst_upd_user
     *
     * @mbggenerated
     */
    private String lstUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.lst_upd_time
     *
     * @mbggenerated
     */
    private Date lstUpdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.lst_upd_date
     *
     * @mbggenerated
     */
    private Date lstUpdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.rec_status
     *
     * @mbggenerated
     */
    private String recStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.scr_level
     *
     * @mbggenerated
     */
    private String scrLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.RESOURCE_ID
     *
     * @return the value of resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.RESOURCE_ID
     *
     * @param resourceId the value for resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.url
     *
     * @return the value of resource.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.url
     *
     * @param url the value for resource.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.description
     *
     * @return the value of resource.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.description
     *
     * @param description the value for resource.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.icon
     *
     * @return the value of resource.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.icon
     *
     * @param icon the value for resource.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.pid
     *
     * @return the value of resource.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.pid
     *
     * @param pid the value for resource.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.seq
     *
     * @return the value of resource.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.seq
     *
     * @param seq the value for resource.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.state
     *
     * @return the value of resource.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.state
     *
     * @param state the value for resource.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.resourcetype
     *
     * @return the value of resource.resourcetype
     *
     * @mbggenerated
     */
    public Integer getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.resourcetype
     *
     * @param resourcetype the value for resource.resourcetype
     *
     * @mbggenerated
     */
    public void setResourcetype(Integer resourcetype) {
        this.resourcetype = resourcetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.crt_user
     *
     * @return the value of resource.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.crt_user
     *
     * @param crtUser the value for resource.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.crt_time
     *
     * @return the value of resource.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.crt_time
     *
     * @param crtTime the value for resource.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.lst_upd_user
     *
     * @return the value of resource.lst_upd_user
     *
     * @mbggenerated
     */
    public String getLstUpdUser() {
        return lstUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.lst_upd_user
     *
     * @param lstUpdUser the value for resource.lst_upd_user
     *
     * @mbggenerated
     */
    public void setLstUpdUser(String lstUpdUser) {
        this.lstUpdUser = lstUpdUser == null ? null : lstUpdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.lst_upd_time
     *
     * @return the value of resource.lst_upd_time
     *
     * @mbggenerated
     */
    public Date getLstUpdTime() {
        return lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.lst_upd_time
     *
     * @param lstUpdTime the value for resource.lst_upd_time
     *
     * @mbggenerated
     */
    public void setLstUpdTime(Date lstUpdTime) {
        this.lstUpdTime = lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.lst_upd_date
     *
     * @return the value of resource.lst_upd_date
     *
     * @mbggenerated
     */
    public Date getLstUpdDate() {
        return lstUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.lst_upd_date
     *
     * @param lstUpdDate the value for resource.lst_upd_date
     *
     * @mbggenerated
     */
    public void setLstUpdDate(Date lstUpdDate) {
        this.lstUpdDate = lstUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.rec_status
     *
     * @return the value of resource.rec_status
     *
     * @mbggenerated
     */
    public String getRecStatus() {
        return recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.rec_status
     *
     * @param recStatus the value for resource.rec_status
     *
     * @mbggenerated
     */
    public void setRecStatus(String recStatus) {
        this.recStatus = recStatus == null ? null : recStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.scr_level
     *
     * @return the value of resource.scr_level
     *
     * @mbggenerated
     */
    public String getScrLevel() {
        return scrLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.scr_level
     *
     * @param scrLevel the value for resource.scr_level
     *
     * @mbggenerated
     */
    public void setScrLevel(String scrLevel) {
        this.scrLevel = scrLevel == null ? null : scrLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceId=").append(resourceId);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", description=").append(description);
        sb.append(", icon=").append(icon);
        sb.append(", pid=").append(pid);
        sb.append(", seq=").append(seq);
        sb.append(", state=").append(state);
        sb.append(", resourcetype=").append(resourcetype);
        sb.append(", crtUser=").append(crtUser);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", lstUpdUser=").append(lstUpdUser);
        sb.append(", lstUpdTime=").append(lstUpdTime);
        sb.append(", lstUpdDate=").append(lstUpdDate);
        sb.append(", recStatus=").append(recStatus);
        sb.append(", scrLevel=").append(scrLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}