package com.bd.model;

import java.io.Serializable;
import java.util.Date;

public class RolePermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.USERID
     *
     * @mbggenerated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.PERMID
     *
     * @mbggenerated
     */
    private String permid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.CRT_TIME
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.LST_UPD_USER
     *
     * @mbggenerated
     */
    private String lstUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.LST_UPD_TIME
     *
     * @mbggenerated
     */
    private Date lstUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.ROLE_ID
     *
     * @return the value of role_permission.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.ROLE_ID
     *
     * @param roleId the value for role_permission.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.USERID
     *
     * @return the value of role_permission.USERID
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.USERID
     *
     * @param userid the value for role_permission.USERID
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.PERMID
     *
     * @return the value of role_permission.PERMID
     *
     * @mbggenerated
     */
    public String getPermid() {
        return permid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.PERMID
     *
     * @param permid the value for role_permission.PERMID
     *
     * @mbggenerated
     */
    public void setPermid(String permid) {
        this.permid = permid == null ? null : permid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.CRT_TIME
     *
     * @return the value of role_permission.CRT_TIME
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.CRT_TIME
     *
     * @param crtTime the value for role_permission.CRT_TIME
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.LST_UPD_USER
     *
     * @return the value of role_permission.LST_UPD_USER
     *
     * @mbggenerated
     */
    public String getLstUpdUser() {
        return lstUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.LST_UPD_USER
     *
     * @param lstUpdUser the value for role_permission.LST_UPD_USER
     *
     * @mbggenerated
     */
    public void setLstUpdUser(String lstUpdUser) {
        this.lstUpdUser = lstUpdUser == null ? null : lstUpdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.LST_UPD_TIME
     *
     * @return the value of role_permission.LST_UPD_TIME
     *
     * @mbggenerated
     */
    public Date getLstUpdTime() {
        return lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.LST_UPD_TIME
     *
     * @param lstUpdTime the value for role_permission.LST_UPD_TIME
     *
     * @mbggenerated
     */
    public void setLstUpdTime(Date lstUpdTime) {
        this.lstUpdTime = lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", userid=").append(userid);
        sb.append(", permid=").append(permid);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", lstUpdUser=").append(lstUpdUser);
        sb.append(", lstUpdTime=").append(lstUpdTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}