package com.bd.model;

import java.io.Serializable;
import java.util.Date;

public class RoleInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.seq
     *
     * @mbggenerated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.isdefault
     *
     * @mbggenerated
     */
    private Integer isdefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.lst_upd_user
     *
     * @mbggenerated
     */
    private String lstUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.lst_upd_time
     *
     * @mbggenerated
     */
    private Date lstUpdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.lst_upd_date
     *
     * @mbggenerated
     */
    private Date lstUpdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.rec_status
     *
     * @mbggenerated
     */
    private String recStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.scr_level
     *
     * @mbggenerated
     */
    private String scrLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.ROLE_ID
     *
     * @return the value of role_info.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.ROLE_ID
     *
     * @param roleId the value for role_info.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.name
     *
     * @return the value of role_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.name
     *
     * @param name the value for role_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.seq
     *
     * @return the value of role_info.seq
     *
     * @mbggenerated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.seq
     *
     * @param seq the value for role_info.seq
     *
     * @mbggenerated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.description
     *
     * @return the value of role_info.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.description
     *
     * @param description the value for role_info.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.isdefault
     *
     * @return the value of role_info.isdefault
     *
     * @mbggenerated
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.isdefault
     *
     * @param isdefault the value for role_info.isdefault
     *
     * @mbggenerated
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.crt_user
     *
     * @return the value of role_info.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.crt_user
     *
     * @param crtUser the value for role_info.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.crt_time
     *
     * @return the value of role_info.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.crt_time
     *
     * @param crtTime the value for role_info.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.lst_upd_user
     *
     * @return the value of role_info.lst_upd_user
     *
     * @mbggenerated
     */
    public String getLstUpdUser() {
        return lstUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.lst_upd_user
     *
     * @param lstUpdUser the value for role_info.lst_upd_user
     *
     * @mbggenerated
     */
    public void setLstUpdUser(String lstUpdUser) {
        this.lstUpdUser = lstUpdUser == null ? null : lstUpdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.lst_upd_time
     *
     * @return the value of role_info.lst_upd_time
     *
     * @mbggenerated
     */
    public Date getLstUpdTime() {
        return lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.lst_upd_time
     *
     * @param lstUpdTime the value for role_info.lst_upd_time
     *
     * @mbggenerated
     */
    public void setLstUpdTime(Date lstUpdTime) {
        this.lstUpdTime = lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.lst_upd_date
     *
     * @return the value of role_info.lst_upd_date
     *
     * @mbggenerated
     */
    public Date getLstUpdDate() {
        return lstUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.lst_upd_date
     *
     * @param lstUpdDate the value for role_info.lst_upd_date
     *
     * @mbggenerated
     */
    public void setLstUpdDate(Date lstUpdDate) {
        this.lstUpdDate = lstUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.rec_status
     *
     * @return the value of role_info.rec_status
     *
     * @mbggenerated
     */
    public String getRecStatus() {
        return recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.rec_status
     *
     * @param recStatus the value for role_info.rec_status
     *
     * @mbggenerated
     */
    public void setRecStatus(String recStatus) {
        this.recStatus = recStatus == null ? null : recStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.scr_level
     *
     * @return the value of role_info.scr_level
     *
     * @mbggenerated
     */
    public String getScrLevel() {
        return scrLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.scr_level
     *
     * @param scrLevel the value for role_info.scr_level
     *
     * @mbggenerated
     */
    public void setScrLevel(String scrLevel) {
        this.scrLevel = scrLevel == null ? null : scrLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", name=").append(name);
        sb.append(", seq=").append(seq);
        sb.append(", description=").append(description);
        sb.append(", isdefault=").append(isdefault);
        sb.append(", crtUser=").append(crtUser);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", lstUpdUser=").append(lstUpdUser);
        sb.append(", lstUpdTime=").append(lstUpdTime);
        sb.append(", lstUpdDate=").append(lstUpdDate);
        sb.append(", recStatus=").append(recStatus);
        sb.append(", scrLevel=").append(scrLevel);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}