package com.bd.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.loginname
     *
     * @mbggenerated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.usertype
     *
     * @mbggenerated
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.isdefault
     *
     * @mbggenerated
     */
    private Integer isdefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.organization_id
     *
     * @mbggenerated
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.lst_upd_user
     *
     * @mbggenerated
     */
    private String lstUpdUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.lst_upd_time
     *
     * @mbggenerated
     */
    private Date lstUpdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.rec_status
     *
     * @mbggenerated
     */
    private String recStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.scr_level
     *
     * @mbggenerated
     */
    private String scrLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.lst_login_time
     *
     * @mbggenerated
     */
    private Date lstLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.USER_ID
     *
     * @return the value of user_info.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.USER_ID
     *
     * @param userId the value for user_info.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.loginname
     *
     * @return the value of user_info.loginname
     *
     * @mbggenerated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.loginname
     *
     * @param loginname the value for user_info.loginname
     *
     * @mbggenerated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.usertype
     *
     * @return the value of user_info.usertype
     *
     * @mbggenerated
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.usertype
     *
     * @param usertype the value for user_info.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.isdefault
     *
     * @return the value of user_info.isdefault
     *
     * @mbggenerated
     */
    public Integer getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.isdefault
     *
     * @param isdefault the value for user_info.isdefault
     *
     * @mbggenerated
     */
    public void setIsdefault(Integer isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.state
     *
     * @return the value of user_info.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.state
     *
     * @param state the value for user_info.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.organization_id
     *
     * @return the value of user_info.organization_id
     *
     * @mbggenerated
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.organization_id
     *
     * @param organizationId the value for user_info.organization_id
     *
     * @mbggenerated
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.crt_user
     *
     * @return the value of user_info.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.crt_user
     *
     * @param crtUser the value for user_info.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser == null ? null : crtUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.crt_time
     *
     * @return the value of user_info.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.crt_time
     *
     * @param crtTime the value for user_info.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.lst_upd_user
     *
     * @return the value of user_info.lst_upd_user
     *
     * @mbggenerated
     */
    public String getLstUpdUser() {
        return lstUpdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.lst_upd_user
     *
     * @param lstUpdUser the value for user_info.lst_upd_user
     *
     * @mbggenerated
     */
    public void setLstUpdUser(String lstUpdUser) {
        this.lstUpdUser = lstUpdUser == null ? null : lstUpdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.lst_upd_time
     *
     * @return the value of user_info.lst_upd_time
     *
     * @mbggenerated
     */
    public Date getLstUpdTime() {
        return lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.lst_upd_time
     *
     * @param lstUpdTime the value for user_info.lst_upd_time
     *
     * @mbggenerated
     */
    public void setLstUpdTime(Date lstUpdTime) {
        this.lstUpdTime = lstUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.rec_status
     *
     * @return the value of user_info.rec_status
     *
     * @mbggenerated
     */
    public String getRecStatus() {
        return recStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.rec_status
     *
     * @param recStatus the value for user_info.rec_status
     *
     * @mbggenerated
     */
    public void setRecStatus(String recStatus) {
        this.recStatus = recStatus == null ? null : recStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.scr_level
     *
     * @return the value of user_info.scr_level
     *
     * @mbggenerated
     */
    public String getScrLevel() {
        return scrLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.scr_level
     *
     * @param scrLevel the value for user_info.scr_level
     *
     * @mbggenerated
     */
    public void setScrLevel(String scrLevel) {
        this.scrLevel = scrLevel == null ? null : scrLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.lst_login_time
     *
     * @return the value of user_info.lst_login_time
     *
     * @mbggenerated
     */
    public Date getLstLoginTime() {
        return lstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.lst_login_time
     *
     * @param lstLoginTime the value for user_info.lst_login_time
     *
     * @mbggenerated
     */
    public void setLstLoginTime(Date lstLoginTime) {
        this.lstLoginTime = lstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", loginname=").append(loginname);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", usertype=").append(usertype);
        sb.append(", isdefault=").append(isdefault);
        sb.append(", state=").append(state);
        sb.append(", organizationId=").append(organizationId);
        sb.append(", crtUser=").append(crtUser);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", lstUpdUser=").append(lstUpdUser);
        sb.append(", lstUpdTime=").append(lstUpdTime);
        sb.append(", recStatus=").append(recStatus);
        sb.append(", scrLevel=").append(scrLevel);
        sb.append(", lstLoginTime=").append(lstLoginTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}